create table customer (notes varchar(255), phone_number varchar(255), id bigint not null, primary key (id));
create table employee (id bigint not null, primary key (id));
create table employee_days_available (employee_id bigint not null, days_available varchar(255));
create table employee_skills (employee_id bigint not null, skills varchar(255));
create table hibernate_sequence (next_val bigint);
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
create table pet (id bigint not null, birth_date date, name nvarchar(255), notes varchar(255), type integer, user_id bigint, primary key (id));
create table schedule (id bigint not null, date date not null, primary key (id));
create table schedule_activities (schedule_id bigint not null, activities varchar(255));
create table schedule_employees (schedule_id bigint not null, schedule_employees_id bigint not null);
create table schedule_pets (schedule_id bigint not null, schedule_pets_id bigint not null);
create table user (id bigint not null, name nvarchar(255), primary key (id));
alter table customer add constraint FKg2o3t8h0g17smtr9jgypagdtv foreign key (id) references user (id);
alter table employee add constraint FKd8il4lxw1wi74qh8b7uoy6e0a foreign key (id) references user (id);
alter table employee_days_available add constraint FK7ra3ha8r7rcikm5k4ow91hluk foreign key (employee_id) references employee (id);
alter table employee_skills add constraint FKnepe51hewn4dd673e3qk1v2qx foreign key (employee_id) references employee (id);
alter table pet add constraint FK9hxka0oqkd15dmqstdarori08 foreign key (user_id) references user (id);
alter table schedule_activities add constraint FKp4gtwmuodj21fo9kjww5ql477 foreign key (schedule_id) references schedule (id);
alter table schedule_employees add constraint FK4jqdj2k803ttskcq59hqac5xn foreign key (schedule_employees_id) references schedule (id);
alter table schedule_employees add constraint FKt3g2am6vtlcfggfaagk8micwx foreign key (schedule_id) references employee (id);
alter table schedule_pets add constraint FKc0ae4itecnaci4jyxgd9tk4un foreign key (schedule_pets_id) references schedule (id);
alter table schedule_pets add constraint FKaqjnkmmrcs7ppachvr1d1kg2v foreign key (schedule_id) references pet (id);